In [1]:
import pandas as pd
from datetime import datetime

In [37]:
from sklearn.decomposition import PCA
from numpy import corrcoef

In [3]:
data=pd.read_csv("close_prices.csv")
index=pd.read_csv("djia_index.csv")

In [4]:
data.date=[datetime.strptime(x,"%Y-%m-%d") for x in data.date.values]

In [5]:
data=data.iloc[0:,1:]

In [18]:
data.head()

,AXP,BA,CAT,CSCO,CVX,DD,DIS,GE,GS,HD,...,PFE,PG,T,TRV,UNH,UTX,V,VZ,WMT,XOM
0,76.440002,117.510002,85.029999,24.270000,125.519997,59.409999,64.750000,24.280001,165.250000,75.910004,...,28.799999,79.279999,34.220001,86.379997,71.820000,109.419998,196.240005,47.980000,76.419998,87.750000
1,76.070000,119.000000,85.110001,24.139999,124.489998,59.319997,64.320000,24.320000,162.970001,76.040001,...,28.709999,78.620003,34.090000,85.870003,72.320000,110.000000,193.339996,47.270000,75.750000,87.360001
2,75.989998,118.510002,84.500000,24.430000,124.070000,59.319997,64.449997,24.230000,162.309998,75.519997,...,28.490000,77.720001,34.049999,85.980003,71.980003,109.260002,191.559998,46.950001,74.650002,87.139999
3,76.320000,119.379997,84.199997,23.770000,123.489998,59.509996,65.239998,24.250000,162.289993,76.070000,...,28.520000,78.050003,34.230000,85.830002,72.160004,109.660004,193.559998,47.669998,74.620003,87.070000
4,75.889999,118.739998,83.800003,23.330000,122.639999,59.009995,65.190002,24.049999,159.850006,75.959999,...,28.879999,77.209999,33.980000,85.410004,71.989998,109.360001,193.050003,47.000000,74.360001,86.900002

In [7]:
pca=PCA(n_components=10)

In [8]:
pca.fit(X=data)

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [13]:
sum=0
for x in pca.explained_variance_ratio_:
    print x
    sum+=x
    print sum
    print

0.738971182715
0.738971182715

0.110071690099
0.849042872814

0.0499508827698
0.898993755584

0.0287491981999
0.927742953784

0.0221544788796
0.949897432663

0.0193157665104
0.969213199174

0.00674853156326
0.975961730737

0.0061409101866
0.982102640924

0.00320594168568
0.985308582609

0.00305611030158
0.988364692911

In [43]:
with open("a1.txt","w") as f:
    f.write("4")

# 3 - 4

In [11]:
a=pca.transform(X=data)

In [12]:
data2=pd.DataFrame(a)

In [14]:
data2.head()

,0,1,2,3,4,5,6,7,8,9
0,-50.902404,17.631677,7.736021,2.596010,2.377569,4.244055,12.883088,3.556570,-5.821974,-1.726040
1,-52.846909,19.146907,7.272546,4.618575,0.102182,3.935519,11.062930,3.432599,-5.633181,-2.012232
2,-54.614439,19.927358,8.109958,4.920347,-0.421454,4.555335,10.119224,4.175203,-5.388287,-2.752699
3,-52.600566,19.941571,6.948113,4.806243,0.319779,5.065505,9.849605,3.266579,-5.974574,-1.922746
4,-52.370123,22.289064,8.410868,3.833372,-2.464882,4.359897,7.988691,3.452709,-5.745204,-1.875131

In [28]:
index=pd.read_csv("djia_index.csv")

In [29]:
index.head()

         date          ^DJI
0  2013-09-23  15401.379883
1  2013-09-24  15334.589844
2  2013-09-25  15273.259766
3  2013-09-26  15328.299805
4  2013-09-27  15258.240234

In [35]:
x=data2[0]
y=index["^DJI"]

In [51]:
corrcoef([x,y])

array([[ 1.        ,  0.90965222],
       [ 0.90965222,  1.        ]])

In [50]:
with open("a2.txt","w") as f:
    f.write("{}".format(corrcoef([x,y])[0][1]))

# 5

In [20]:
compon=pd.DataFrame(pca.components_)

In [23]:
compon

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.016138,0.120645,-0.051661,0.050484,-0.125860,0.114090,0.233906,-0.006205,0.251227,0.288996,...,0.023092,0.077732,-0.007206,0.189480,0.321564,0.053683,0.579684,0.000109,0.087161,-0.042942
1,-0.233026,0.138102,-0.564736,-0.029421,-0.297156,-0.070072,-0.241633,-0.022603,-0.105527,0.031603,...,0.040701,-0.018652,-0.035559,-0.076710,-0.054117,-0.001830,0.106388,-0.032192,0.050303,-0.257983
2,-0.105902,-0.473845,-0.053749,0.007206,-0.048401,-0.066652,-0.045366,-0.031786,0.348309,0.142316,...,-0.070711,0.135307,-0.001104,0.091877,0.072012,-0.433768,-0.375350,0.022252,-0.012916,-0.164835
3,-0.326936,0.445168,-0.230866,0.055920,0.124084,0.098464,0.219909,0.002888,-0.051801,0.306424,...,0.005825,-0.040714,0.051274,0.189204,0.297421,0.021500,-0.510710,0.055608,0.025815,-0.040676
4,0.075447,0.315744,-0.171772,-0.053438,0.173984,-0.085211,-0.097893,0.054917,0.671926,0.052464,...,0.025303,0.005582,-0.000559,-0.134825,-0.228641,-0.141343,0.156346,0.058715,-0.053339,0.079863
5,-0.147876,-0.279149,0.014168,0.010084,-0.350357,0.092711,0.293251,-0.084395,-0.021326,0.157150,...,0.025731,-0.191953,-0.073691,-0.273096,0.221092,0.010516,0.143472,-0.098254,-0.177974,-0.234524
6,-0.179904,-0.393784,-0.311796,0.121400,0.357219,-0.129996,-0.270408,-0.042259,-0.079742,-0.075878,...,0.015718,0.177825,0.056535,0.165581,0.190734,0.099172,0.221706,-0.032406,0.297354,0.013115
7,-0.216013,-0.031168,0.129445,0.085260,0.469641,-0.225414,0.203127,-0.037389,0.024838,0.001730,...,-0.087559,-0.368124,-0.020983,0.018706,0.085108,-0.193647,0.153700,0.074934,-0.359775,-0.002826
8,0.072390,0.154913,-0.184295,-0.092323,-0.126029,-0.130846,0.110639,-0.060706,-0.094523,0.021487,...,-0.034236,0.119463,-0.079009,-0.165713,-0.129312,-0.143828,-0.074481,-0.115317,0.136362,0.354565
9,-0.371273,0.213223,0.187313,0.099688,-0.133616,-0.050084,0.015771,0.016710,-0.276203,-0.073120,...,-0.061836,0.100373,0.103843,0.040258,-0.299245,-0.509063,0.289465,0.124859,0.059090,-0.118009

In [25]:
compon.max(axis=1)

0    0.579684
1    0.138102
2    0.348309
3    0.445168
4    0.671926
5    0.484027
6    0.361613
7    0.469641
8    0.354565
9    0.289465
dtype: float64

In [44]:
with open("a3.txt","w") as f:
    f.write("V")